import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "./components/navbar";

const MainPage: NextPage = () => {
  return (
    <>
      <div className="container mx-auto">
        <Head>
          <title>Naranjo Express</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/naranjo-express-transparent.png" />
        </Head>
        <Navbar />
        <main className="bg-gray-100">

        </main>
      </div>

    </>
  );
};

export default MainPage;